title: Naming the Code
markdown: kramdown

# for atom feed
author:
  name: Lucas Dom√≠nguez Carballo
  email: lucasdct10@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title

exclude: ["*.py", "sitemap.xml", "feed.xml", "LICENSE", "README.md"]
